### ISSUE TITLE
add thumb to this slider?

### ISSUE THREAD

**Issue by Azinnilchi** [iSapozhnik/SegmentedProgressView#2]
hi, I have searched a lot for this type of progress bar! thanks, it's perfect! but is there a way to add a thumb to this progress bar?! and set it exactly to stop on the segment white space?! thank you very much!

**Comment by iSapozhnik** [comment]
Hey @Azinnilchi ! Thanks for the feedback. There is a new version coming soon - refactored and cleaned up. Regarding your question - I will think about it. So the idea is to have a small circle in the beginning of each segment and when the segment starts 'playing' the thumb should start moving accordingly, am I right ?

**Comment by Azinnilchi** [comment]
hey, thank you for your response! yeap! you've got my Idea! I had a solution for this in my mind, my solution is to use a slider above it, and set the track of the slider transparent! and also we can set the progress to jump in every segment! with a thumb! it's a beautiful design!

**Comment by iSapozhnik** [comment]
@Azinnilchi please check develop branch.
